service: cloudfront-apigw
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    MyDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Origins:
            - Id: MyApiGateway
              DomainName: !Join
                - "."
                - - !Ref HttpApi
                  - execute-api
                  - !Ref AWS::Region
                  - amazonaws.com
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
          DefaultCacheBehavior:
            TargetOriginId: MyApiGateway
            ViewerProtocolPolicy: https-only
            ForwardedValues:
              QueryString: false
            # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html#managed-cache-policy-caching-disabled
            # CachingDisabled
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-origin-request-policies.html
            # AllViewerExceptHostHeader
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac
          ViewerCertificate:
            MinimumProtocolVersion: TLSv1.2_2018
            CloudFrontDefaultCertificate: true