service: pem-to-envvar

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
    environment:
      PEM: ${file(pem.js):pem}
